lname: Atualizar HTML automaticamente

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/30 * * * *" # roda a cada 30 minutos (pode mudar depois)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências (opcional)
      run: |
        pip install pandas
        pip install requests

    - name: Rodar script Python
      run: python perfil.py

    - name: Commitar alterações
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Atualização automática" || echo "Nada para commitar"
        git push
